# python cnn_classifier.py fit -c config.yaml
# python cnn_classifier.py predict -c config.yaml --ckpt_path <checkpoint_path>
model:
  num_classes: 100
  learning_rate: 3e-5
  weight_decay: 1.2e-3
  label_smoothing: 0.15

data:
  batch_size: 128
  num_workers: 8
  val_size: 0.2

trainer:
  max_epochs: 100
  accelerator: auto
  devices: auto
  strategy: auto
  precision: 32-true
  check_val_every_n_epoch: 1
  num_sanity_val_steps: 1
  log_every_n_steps: 10
  enable_progress_bar: true
  enable_checkpointing: true

run_name: cnn_butterflies_new
output_path: submission.csv
seed_everything: 0
# ckpt_path: runs/cnn_butterflies_new/best_cnn-v2.ckpt
